---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.40.2
  replicas: 3
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --dbfilename=dump
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --default_lua_flags=allow-undeclared-keys
  networkPolicyEnabled: false
  resources:
    requests:
      cpu: 30m
    limits:
      memory: 512Mi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: dragonfly
  serviceSpec:
    annotations:
      gatus.home-operations.com/enabled: "true"
      gatus.home-operations.com/endpoint: |
        conditions:
          - "[CONNECTED] == true"
        group: infrastructure
        ui:
          hide-url: true
          hide-hostname: true
        alerts:
          - type: pushover
            send-on-resolved: true
