---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: tempo
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    tempo:
      reportingEnabled: false
      metricsGenerator:
        enabled: true
        remoteWriteUrl: "http://kube-prometheus-stack-prometheus.monitoring:9090/api/v1/write"
      storage:
        trace:
          backend: s3
          s3:
            insecure: false

    serviceMonitor:
      enabled: true

    persistence:
      enabled: false

  valuesFrom:
    - kind: Secret
      name: tempo-secret
      valuesKey: S3_BUCKET_NAME
      targetPath: tempo.storage.trace.s3.bucket
    - kind: Secret
      name: tempo-secret
      valuesKey: S3_BUCKET_HOST
      targetPath: tempo.storage.trace.s3.endpoint
    - kind: Secret
      name: tempo-secret
      valuesKey: S3_BUCKET_REGION
      targetPath: tempo.storage.trace.s3.region
    - kind: Secret
      name: tempo-secret
      valuesKey: S3_ACCESS_KEY
      targetPath: tempo.storage.trace.s3.access_key
    - kind: Secret
      name: tempo-secret
      valuesKey: S3_SECRET_KEY
      targetPath: tempo.storage.trace.s3.secret_key
