---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

# TODO: Clean up `--context` usage
# https://github.com/go-task/task/issues/1038

env:
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"
  KUBECONFIG: "{{.KUBERNETES_DIR}}/main/kubeconfig"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  TALOS_DIR: "{{.ROOT_DIR}}/kubernetes/main/talos"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/terraform"

includes:
  brew:
    taskfile: .taskfiles/Brew/Taskfile.yaml
  external-secrets:
    taskfile: .taskfiles/ExternalSecrets/Taskfile.yaml
  flux:
    taskfile: .taskfiles/Flux/Taskfile.yaml
  kubernetes:
    taskfile: .taskfiles/Kubernetes/Taskfile.yaml
  postgres:
    taskfile: .taskfiles/Postgres/Taskfile.yaml
  rook:
    taskfile: .taskfiles/Rook/Taskfile.yaml
  talos:
    taskfile: .taskfiles/Talos/Taskfile.yaml
  volsync:
    taskfile: .taskfiles/VolSync/Taskfile.yaml

tasks:

  default:
    silent: true
    cmd: task -l
