---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lazylibrarian
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      lazylibrarian:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/lazylibrarian
              tag: latest
            env:
              TZ: Europe/Oslo
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 500Mi
    service:
      app:
        controller: lazylibrarian
        ports:
          http:
            port: &port 5299
    route:
      app:
        hostnames: ["{{ .Release.Name }}.rodent.cc"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        existingClaim: lazylibrarian
      media:
        type: nfs
        server: tank.internal
        path: /mnt/tank/Media
        globalMounts:
          - path: /downloads
            subPath: Downloads
          - path: /books
            subPath: Media/Books
