---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pinepods
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pinepods-secret
    template:
      data:
        # Default admin user
        USERNAME: "{{ .PINEPODS_ADMIN_USERNAME }}"
        PASSWORD: "{{ .PINEPODS_ADMIN_PASSWORD }}"
        FULLNAME: "{{ .PINEPODS_ADMIN_FULLNAME }}"
        EMAIL: "{{ .PINEPODS_ADMIN_EMAIL }}"
        # DB
        DB_TYPE: "postgresql"
        DB_HOST: &dbHost postgres-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: &dbUser "{{ .PINEPODS_POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .PINEPODS_POSTGRES_PASSWORD }}"
        DB_NAME: &dbName pinepods
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: pinepods
    - extract:
        key: cloudnative-pg
