---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wallos
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      wallos:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/ellite/wallos
              tag: 3.2.0@sha256:37ac7eca26ae93531d89e462d32ca0a59497c85191343d4b968ce2894b63f9de
            env:
              TZ: Europe/Oslo
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    service:
      app:
        controller: wallos
        ports:
          http:
            port: &port 80
    route:
      app:
        hostnames: ["{{ .Release.Name }}.rodent.cc"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: wallos
        advancedMounts:
          wallos:
            app:
              - path: /var/www/html/db
                subPath: db
              - path: /var/www/html/images/uploads/logos
                subPath: logos
