---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vpa
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    recommender:
      image:
        repository: registry.k8s.io/autoscaling/vpa-recommender
        tag: 0.14.0
      enabled: true
      extraArgs:
        storage: prometheus
        prometheus-address: http://thanos-query.monitoring.svc.cluster.local:9090
        # https://github.com/kubernetes/autoscaler/issues/5031#issuecomment-1450583325
        prometheus-cadvisor-job-name: kubelet
        container-pod-name-label: pod
        container-name-label: container
        metric-for-pod-labels: kube_pod_labels{job="kube-state-metrics"}[8d]
        pod-namespace-label: namespace
        pod-name-label: pod
    updater:
      enabled: false
    admissionController:
      enabled: false
