---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: convertx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: convertx-secret
    template:
      data:
        # App
        JWT_SECRET: "{{ .CONVERTX_JWT_SECRET }}"
  dataFrom:
    - extract:
        key: convertx
