---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-secret
    template:
      data:
        # App
        DB_DATABASE_NAME: &dbName immich
        DB_HOSTNAME: &dbHost postgres-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USERNAME: &dbUser "{{ .DB_USERNAME }}"
        DB_PASSWORD: &dbPass "{{ .DB_PASSWORD }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: cloudnative-pg
