---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: immich
spec:
  spec:
    devices:
      requests:
        - name: gpu
          exactly:
            deviceClassName: gpu.intel.com
