---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
spec:
  chartRef:
    kind: OCIRepository
    name: barman-cloud
  interval: 1h
  values:
    crds:
      create: true
    rbac:
      create: true
