AUTHENTICATION_SOURCES = ['oauth2']
OAUTH2_AUTO_CREATE_USER = True
MASTER_PASSWORD_REQUIRED = False

OAUTH2_CONFIG = [{
  'OAUTH2_NAME': 'authentik',
  'OAUTH2_DISPLAY_NAME': 'Authentik',
  'OAUTH2_CLIENT_ID': '{{ .PGADMIN_OAUTH2_CLIENT_ID }}',
  'OAUTH2_CLIENT_SECRET': '{{ .PGADMIN_OAUTH2_CLIENT_SECRET }}',
  'OAUTH2_TOKEN_URL': '{{ .PGADMIN_OAUTH2_TOKEN_URL }}',
  'OAUTH2_AUTHORIZATION_URL': '{{ .PGADMIN_OAUTH2_AUTHORIZATION_URL }}',
  'OAUTH2_USERINFO_ENDPOINT': '{{ .PGADMIN_OAUTH2_USERINFO_ENDPOINT }}',
  'OAUTH2_SERVER_METADATA_URL': '{{ .PGADMIN_OAUTH2_SERVER_METADATA_URL }}',
  'OAUTH2_API_BASE_URL': '{{ .PGADMIN_OAUTH2_API_BASE_URL }}',
  'OAUTH2_SCOPE': 'openid email profile'
}]
