---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbtools
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: media
  values:
    controllers:
      tagging:
        type: cronjob
        cronjob: &cronJobSpec
          schedule: 0 * * * *
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 3600
        initContainers:
          tag: &container
            image:
              repository: ghcr.io/buroa/qbtools
              tag: v0.19.14@sha256:905617dfc1a8aa1510381d8e177cc5581a49bfa9d56f3f05e0574f6c83987d3c
            env:
              QBITTORRENT_HOST: qbittorrent.media.svc.cluster.local
              QBITTORRENT_PORT: 80
            args:
              [
                "tagging",
                "--added-on",
                "--expired",
                "--last-activity",
                "--sites",
                "--unregistered",
              ]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 256M
        containers:
          unregistered:
            <<: *container
            args:
              [
                "prune",
                "--exclude-tag",
                "added:1d",
                "--include-tag",
                "unregistered",
                "--with-data",
              ]
          expired:
            <<: *container
            args:
              [
                "prune",
                "--exclude-tag",
                "added:1d",
                "--include-tag",
                "expired",
                "--with-data",
              ]
        pod:
          restartPolicy: Never
      orphaned:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: 0 0 * * 0
          suspend: true
        containers:
          app:
            <<: *container
            args: ["orphaned", "--exclude-pattern", "*_unpackerred*"]
        pod:
          restartPolicy: Never
      reannounce:
        containers:
          app:
            <<: *container
            args: ["reannounce", "--process-seeding"]
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
    persistence:
      secret-file:
        type: secret
        name: qbtools-config-secret
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      media:
        type: nfs
        server: tank.internal
        path: /mnt/tank/Media
        advancedMounts:
          orphaned:
            app:
              - path: /media
