---
# yaml-language-server: $schema=https://crd.movishell.pl/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  type: oci
  interval: 30m
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm
