---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxicloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oxicloud-secret
    template:
      data:
        # DB
        DB_DATABASE_NAME: &dbName oxicloud
        DB_HOSTNAME: &dbHost postgres-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USERNAME: &dbUser "{{ .OXICLOUD_DB_USERNAME }}"
        DB_PASSWORD: &dbPass "{{ .OXICLOUD_DB_PASSWORD }}"
        OXICLOUD_DB_CONNECTION_STRING: "postgresql://{{ .OXICLOUD_DB_USERNAME }}:{{ .OXICLOUD_DB_PASSWORD }}@postgres-rw.database.svc.cluster.local:5432/oxicloud"
        # OIDC
        OXICLOUD_OIDC_ISSUER_URL: "{{ .OXICLOUD_OIDC_ISSUER_URL }}"
        OXICLOUD_OIDC_REDIRECT_URI: "{{ .OXICLOUD_OIDC_REDIRECT_URI }}"
        OXICLOUD_OIDC_CLIENT_ID: "{{ .OXICLOUD_OIDC_CLIENT_ID }}"
        OXICLOUD_OIDC_CLIENT_SECRET: "{{ .OXICLOUD_OIDC_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # R2
        OXICLOUD_S3_BUCKET: "{{ .OXICLOUD_S3_BUCKET }}"
        OXICLOUD_S3_ENDPOINT_URL: "{{ .OXICLOUD_S3_ENDPOINT_URL }}"
        OXICLOUD_S3_ACCESS_KEY: "{{ .OXICLOUD_S3_ACCESS_KEY }}"
        OXICLOUD_S3_SECRET_KEY: "{{ .OXICLOUD_S3_SECRET_KEY }}"
        OXICLOUD_STORAGE_ENCRYPTION_KEY: "{{ .OXICLOUD_STORAGE_ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: oxicloud
    - extract:
        key: cloudnative-pg
