---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: k8s-monitoring-secret
    template:
      engineVersion: v2
      data:
        K8S_PROM_USER: "{{ .K8S_PROM_USER }}"
        K8S_LOKI_USER: "{{ .K8S_LOKI_USER }}"
        K8S_TOKEN: "{{ .K8S_TOKEN }}"
        K8S_PROM_HOST: "{{ .K8S_PROM_HOST }}"
        K8S_LOKI_HOST: "{{ .K8S_LOKI_HOST }}"
        K8S_OPENCOST_HOST: "{{ .K8S_OPENCOST_HOST }}"

  dataFrom:
    - extract:
        key: grafana-k8s-monitoring
