---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-monitoring
      version: 0.6.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    prometheus-operator-crds:
      enabled: false
    cluster:
      name: home-ops
    externalServices:
      prometheus:
        secret:
          create: false
          name: k8s-monitoring-secret
        hostKey: K8S_PROM_HOST
        basicAuth:
          usernameKey: K8S_PROM_USER
          passwordKey: K8S_TOKEN
      loki:
        secret:
          create: false
          name: k8s-monitoring-secret
        hostKey: K8S_LOKI_HOST
        basicAuth:
          usernameKey: K8S_LOKI_USER
          passwordKey: K8S_TOKEN
    opencost:
      opencost:
        exporter:
          defaultClusterId: home-ops
        prometheus:
          external:
            url: https://prometheus-prod-39-prod-eu-north-0.grafana.net/api/prom
