---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nut-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    controllers:
      nut-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/druggeri/nut_exporter
              tag: 3.2.0
            env:
              TZ: Europe/Oslo
            args: --nut.vars_enable="battery.charge,battery.charge,battery.runtime,battery.type,device.mfr,device.model,device.type,driver.name,driver.parameter.pollfreq,driver.parameter.pollinterval,driver.parameter.port,driver.parameter.vendorid,driver.version,driver.version.data,driver.version.internal,input.voltage,outlet.1.status,outlet.desc,outlet.id,outlet.switchable,output.frequency,output.frequency.nominal,output.voltage,output.voltage.nominal,ups.beeper.status,ups.delay.shutdown,ups.firmware,ups.load,ups.mfr,ups.model,ups.power.nominal,ups.productid,ups.start.battery,ups.status,ups.timer.shutdown,ups.vendorid,ups.vendorid"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              limits:
                cpu: 100m
                memory: 200Mi
    service:
      app:
        controller: *app
        ports:
          metrics:
            enabled: true
            protocol: TCP
            port: 9199
