---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    template:
      data:
        # DB
        AUTHENTIK_POSTGRESQL__USER: "{{ .AUTHENTIK_POSTGRESQL__USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_POSTGRESQL__PASSWORD }}"
        AUTHENTIK_POSTGRESQL__HOST: &dbhost postgres-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &dbname authentik
        # Email
        AUTHENTIK_EMAIL__HOST: smtp.office365.com
        AUTHENTIK_EMAIL__PORT: "587"
        AUTHENTIK_EMAIL__USE_TLS: "true"
        AUTHENTIK_EMAIL__USERNAME: "{{ .AUTHENTIK_EMAIL__USERNAME }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .AUTHENTIK_EMAIL__PASSWORD }}"
        # Media Storage
        AUTHENTIK_STORAGE__MEDIA__BACKEND: "s3"
        AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: "{{ .AWS_ACCESS_KEY_ID }}"
        AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT: https://d74d8dfc1170c5004e77bb7bb67219a6.r2.cloudflarestorage.com/
        AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME: "authentik"
        # Misc
        AUTHENTIK_SESSION_STORAGE: "db"
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: cloudnative-pg
    - extract:
        key: cloudflare
