---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

metrics: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/24843521
  link: https://github.com/rodent1
  buttons:
    - name: Github
      link: https://github.com/rodent1
    - name: Homelab
      link: https://github.com/rodent1/home-ops

web:
  port: ${GATUS_WEB_PORT}

storage:
  type: sqlite
  path: /config/sqlite.db
