---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  # App
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  # Templates
  - ../../../../templates/gatus/guarded
  - ../../../../templates/volsync
configMapGenerator:
  - name: pgadmin-local-config
    files:
      - config_local.py=./config/config_local.py
  - name: servers-json
    files:
      - ./config/servers.json
generatorOptions:
  disableNameSuffixHash: true
