---
ingress:
  - hostname: rodent.cc
    originRequest:
      originServerName: rodent.cc
    service: https://envoy-external.network.svc.cluster.local:443
  - hostname: "*.rodent.cc"
    originRequest:
      originServerName: external.rodent.cc
    service: https://envoy-external.network.svc.cluster.local:443
  - service: http_status:404
