---
originRequest:
  originServerName: external.rodent.cc

ingress:
  - hostname: rodent.cc
    service: &service https://envoy-external.network.svc.cluster.local
  - hostname: "*.rodent.cc"
    service: *service
  - service: http_status:404
