---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: network-ups-tools
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      network-ups-tools:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/jr0dd/network-ups-tools
              tag: v2.8.3@sha256:9f8e14d155c6ef05940cee6f8861e259e951eb11750aeddd02539d986dac1ca0
            env:
              TZ: Europe/Oslo
            securityContext:
              privileged: true
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
        pod:
          annotations:
            configmap.reloader.stakater.com/reload: &config network-ups-tools-config
          nodeSelector:
            eaton.feature.node.kubernetes.io/ups: "true"
    service:
      app:
        controller: network-ups-tools
        ports:
          http:
            port: 3493
            protocol: TCP
    persistence:
      config:
        enabled: true
        type: configMap
        name: *config
        globalMounts:
          - path: /etc/nut
            readOnly: true
