---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ai
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: paperless-ai
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      paperless-ai:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/clusterzx/paperless-ai
              tag: 3.0.7
            envFrom:
              - secretRef:
                  name: paperless-ai-secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    service:
      app:
        ports:
          http:
            port: &port 3000
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.rodent.cc"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/data
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
