[env]
_.file = ["{{config_root}}/.secrets.env"]
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"

[hooks]
postinstall = "lefthook install"

[tools]
"github:home-operations/flate" = "v0.6.5"
actionlint = "1.7.12"
oxfmt = "0.66.0"
talos = "1.14.0"
