[env]
_.file = ["{{config_root}}/.secrets.env"]
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"

[tools]
oxfmt = "0.56.0"
zizmor = "1.25.2"

[hooks]
postinstall = "lefthook install"
