---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex-trakt-sync
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: plex
      namespace: media
  values:
    controllers:
      plex-trakt-sync:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          schedule: "@daily"
          timeZone: Europe/Oslo
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/taxel/plextraktsync
              tag: 0.34.4
            args:
              - sync
            env:
              PLEX_BASEURL: http://plex.media.svc.cluster.local:32400
              PLEX_LOCALURL: http://plex.media.svc.cluster.local:32400
              PLEX_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: trakt-secret
                    key: PLEX_TOKEN
              PLEX_USERNAME: stian.sp
              TRAKT_USERNAME: stian.sp
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 512M
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: plex-trakt-sync
        globalMounts:
          - path: /app/config
      config-yaml:
        type: configMap
        name: plex-trakt-sync
        globalMounts:
          - path: /app/config/config.yml
            subPath: config.yml
            readOnly: true
