---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hoarder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      hoarder:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: 0.22.0@sha256:e2156f3de4a1eafc53afb6e682f20857be4449d7e9d24240afe6d9ccd280ed3b
            env:
              DATA_DIR: /data
              MEILI_ADDR: http://hoarder-meilisearch:7700
              BROWSER_WEB_URL: http://hoarder-chrome:9222
              NEXTAUTH_URL: https://hoarder.rodent.cc
              CRAWLER_DOWNLOAD_BANNER_IMAGE: true
              CRAWLER_ENABLE_ADBLOCKER: true
              CRAWLER_STORE_SCREENSHOT: true
              CRAWLER_FULL_PAGE_ARCHIVE: true
              CRAWLER_FULL_PAGE_SCREENSHOT: true
              CRAWLER_VIDEO_DOWNLOAD: true
              # OAuth setup
              OAUTH_PROVIDER_NAME: Authentik
              DISABLE_PASSWORD_AUTH: true
              DISABLE_NEW_RELEASE_CHECK: true
              # FIXME: Remove this when the following PR is merged and released https://github.com/hoarder-app/hoarder/pull/969/files
              COREPACK_INTEGRITY_KEYS: 0
            envFrom: &envFrom
              - secretRef:
                  name: hoarder-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
          chrome:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
            args:
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            securityContext:
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
          meilisearch:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.13.0
            env:
              MEILI_NO_ANALYTICS: true
            envFrom: *envFrom
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: hoarder
        ports:
          http:
            port: 3000
      chrome:
        controller: hoarder
        ports:
          http:
            port: 9222
      meilisearch:
        controller: hoarder
        ports:
          http:
            port: 7700
    ingress:
      app:
        className: external
        hosts:
          - host: "{{ .Release.Name }}.rodent.cc"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: hoarder
        advancedMounts:
          hoarder:
            app:
              - path: /data
                subPath: hoarder
            meilisearch:
              - path: /meili_data
                subPath: meilisearch
