---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hoarder
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      hoarder:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: 0.23.0@sha256:97903be067ee5e071238894e8f949c587282f26911e27ae216e52a2f85d1ba7f
            env:
              DATA_DIR: /data
              MEILI_ADDR: http://hoarder-meilisearch:7700
              BROWSER_WEB_URL: http://hoarder-chrome:9222
              NEXTAUTH_URL: https://hoarder.rodent.cc
              CRAWLER_DOWNLOAD_BANNER_IMAGE: true
              CRAWLER_ENABLE_ADBLOCKER: true
              CRAWLER_STORE_SCREENSHOT: true
              CRAWLER_FULL_PAGE_ARCHIVE: true
              CRAWLER_FULL_PAGE_SCREENSHOT: true
              CRAWLER_VIDEO_DOWNLOAD: true
              # OAuth setup
              OAUTH_PROVIDER_NAME: Authentik
              DISABLE_PASSWORD_AUTH: true
              DISABLE_NEW_RELEASE_CHECK: true
              # FIXME: Remove this when the following PR is merged and released https://github.com/hoarder-app/hoarder/pull/969/files
              COREPACK_INTEGRITY_KEYS: 0
            envFrom: &envFrom
              - secretRef:
                  name: hoarder-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
      meilisearch:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - hoarder
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - hoarder
                  topologyKey: kubernetes.io/hostname
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.13.3
            env:
              MEILI_NO_ANALYTICS: true
              MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE: true
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: hoarder-secret
                    key: MEILI_MASTER_KEY
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi
      chrome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
            args:
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            securityContext:
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: hoarder
        ports:
          http:
            port: &port 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.rodent.cc"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: hoarder-app
                port: *port
    persistence:
      data:
        existingClaim: hoarder
        advancedMounts:
          hoarder:
            app:
              - path: /data
                subPath: hoarder
          meilisearch:
            app:
              - path: /meili_data
                subPath: meilisearch
