---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
spec:
  chart:
    spec:
      chart: dragonfly-operator
      version: v1.1.10
      sourceRef:
        kind: HelmRepository
        name: dragonfly
        namespace: flux-system
  install:
    crds: CreateReplace
  interval: 1h
  maxHistory: 3
  upgrade:
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    serviceMonitor:
      enabled: false
