---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: goldilocks
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      rbac:
        extraRules:
          - apiGroups: ["ceph.rook.io"]
            resources: ["cephclusters","cephfilesystems","cephobjectstores"]
            verbs: ["list", "get"]
          - apiGroups: ["monitoring.coreos.com"]
            resources: ["alertmanagers", "prometheuses"]
            verbs: ["list", "get"]
          - apiGroups: ["postgresql.cnpg.io"]
            resources: ["clusters"]
            verbs: ["list", "get"]
          - apiGroups: ["actions.github.com"]
            resources: ["ephemeralrunnersets", "autoscalinglisteners"]
            verbs: ["list", "get"]
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 200Mi
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host goldilocks.${SECRET_DOMAIN}
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 200Mi
