---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
spec:
  interval: 1h
  path: ./kubernetes/apps/rook-ceph/rook-ceph/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
spec:
  dependsOn:
    - name: rook-ceph
    - name: volsync
      namespace: volsync-system
  healthCheckExprs:
    - apiVersion: ceph.rook.io/v1
      current: status.ceph.health in ['HEALTH_OK', 'HEALTH_WARN']
      failed: status.ceph.health == 'HEALTH_ERR'
      kind: CephCluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: rook-ceph-cluster
      namespace: rook-ceph
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      name: rook-ceph
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/rook-ceph/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
