---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
spec:
  chartRef:
    kind: OCIRepository
    name: freshrss
  interval: 1h
  values:
    controllers:
      freshrss:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: freshrss/freshrss
              tag: 1.29.1-alpine@sha256:e1c956e586ae20ba7f9a0c6582043172ee084af43f17ff48b8de22ade026b6c4
            env:
              CRON_MIN: "*"
              DOMAIN: freshrss.rodent.cc
              LISTEN: &port 8080
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.rodent.cc"
        parentRefs:
          - name: envoy-external
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          freshrss:
            app:
              - path: /var/www/FreshRSS/data
                subPath: data
                readOnly: false
              - path: /var/www/FreshRSS/extensions
                subPath: extensions
                readOnly: false
      tmpfs:
        type: emptyDir
        advancedMounts:
          freshrss:
            app:
              - path: /var/www/FreshRSS/data/cache
                subPath: cache
